### ISSUE TITLE
Code discussion

### ISSUE THREAD

**Issue by SogeMoge** [talking-dog/TA175-Bot#1]
Hi! Am I getting it right that "Short link" is used as a restriction for bot so that he won't reply to himself?
```
        if (len(linkUrl)>90):
            print("Short Link skipping")
```

**Comment by talking-dog** [comment]
It is partly for that, but mostly it it to allow people to post a link to the website root level without the BOT trying to download a list.

**Comment by SogeMoge** [comment]
I thought that you could simplify code with additional condition and with few extra characters in search string
```
    if message.author.bot: #check that author is not the bot itself
        return
    elif '://xwing-legacy.com/?f' in message.content:
```
